### ISSUE TITLE
FYI: How to connect to a TCP server from an arbitrary Web page in the browser

### ISSUE THREAD

**Issue by guest271314** [GoogleChromeLabs/telnet-client#25]
https://gist.github.com/guest271314/ac9e26f71f5b299baa1b4663002ba9e6

- Using only Web API's https://github.com/guest271314/telnet-client/tree/user-defined-tcpsocket-controller-web-api
- Using browser extension code and Web API's https://github.com/guest271314/telnet-client/tree/user-defined-tcpsocket-controller

Rationale: 

- A `window` cannot really be completely isolated on the Web/in the browser
- Marrying API's (Isoalted Web Apps-Direct Sockets) is hazardous in that users could see the IWA as only a means to an end to use Direct SOckets and thereby break the IWA in order to use Direct SOckets how they see fit
- Options should be provided to user for _the user_ to decide which origins the IWA can communicate with using `opener` and `postMessage()`

**Comment by cmfcmf** [comment]
I think the key here is that for this to work, the IWA must be willing to expose its capabilities to arbitrary web pages via WebRTC. A 'normal' IWA, which doesn't contain such code, would not allow you to access sockets from arbitrary web pages.
You are right in that there are some ways of how an IWA could allow other websites to access its powerful capabilities: E.g., an IWA could probably also use sockets to start a local http server, which arbitrary web pages could then connect to, and thus would allow to expose any IWA functionality to arbitrary web pages.

Similarly, if you go to this amount of effort, you could also always have a server as a proxy between a website with lower capabilities to another website with higher capabilities. In this way, you could also effectively use secure-context-only or IWA-only APIs from an http page. The fact that this is possible doesn't convince me that secure defaults are unnecessary.

**Comment by guest271314** [comment]
The points are 

1. There is no way to truly isolate a `window`;
2. The end-user ultimately decides how a feature is exposed and used, not absentee authors of proposals, specifications or implementers
3. Given 1 and 2 the proposal authors and implementers need to provide a means for the end-user to set which origins to expose the feature on, instead of trying to prevent access by end-users, which is not practically possible.

For me IWA is just a means to an end to use Direct Sockets. I understand that you folks really thingk IWA is important in and of itself, however, that's not my interest. So whatever deterents uou might try to come up with to gate Direct Sockets, I am probably just as motivated to break out of those boxes to get the to Direct Sockets you have decided to marry to IWA.

Since IWA is kind of emulating an extension, we can supply the same mechanism to at least expose `opener` on the IWA so we can make use of transferable streams between the IWA and the origin we set. So inclusing something like `"externally_connectable"` or its Web API equaivalent should suffice to allow end-users to embed the IWA inan `iframe` or open an IWA `window` where `parent` and `opener` are set to the Web page hat opened the IWA. 

You can't really hide behind anything here as to whether or not your prospective isolation model works or not in certain cases. I'm relatively certain I will find a way to get into or get out of the IWA to do what I want with Direct Sockets for my own use cases. So it would be prudent to just expose a direct means to do so to avoid all of the ways you try to isolate being nullified in the field. Remember `chrome.sockets.tcp` was exposed in a basic manifest.json.

**Comment by guest271314** [comment]
So why am I interested in Direct Sockets?

I'm basically trying to implement Native Messaging with Streams in order to compare the efficacy and efficiency of Streams to JSON over IPC, see https://bugs.chromium.org/p/chromium/issues/detail?id=1214621.

**Comment by cmfcmf** [comment]
If I understand your logic correctly, you'd also argue that all extension APIs should be available to all websites without the need for an extension, because you can communicate with extensions and thus use their APIs from arbitrary web pages. Is my understanding correct?

**Comment by guest271314** [comment]
I'm saying its futile to try to gate capabilities behind gates - without exposing _options_ for the user to expose said capabilities. 

Your security model will just wind up being exposedas broken over and over again.

Just write out an _option_ for users to set which site the IWA or whatever is exposed on. 

I think the real problem is specification authors don't trust users and think they know best.

**Comment by cmfcmf** [comment]
I'm not really sure how to move forward here; your tone makes it tough for me to continue responding. An all-encompassing allegation such as "specification authors don't trust users and think they know best" feels like it might not align with Google's [Community Guidelines](https://opensource.google/conduct/) for its Open Source projects. I am sure that many authors of Web Standards, specifications, and proposals, be it at Google, Mozilla, Apple, Microsoft, or at other companies, care deeply about their users.
Again, it is okay and encouraged to respectfully discuss these proposals, but your tone makes me think that a constructive discussion with you might not be possible.

**Comment by reillyeon** [comment]
Closing this issue because supporting connections to TCP servers from arbitrary web pages is a non-goal for the Direct Sockets API.

HTTP and WebSockets are "just wrappers" around a TCP connection however they intentionally limit the hosts that a page can connect to. Remember that a web page can run arbitrary code on your computer. This code has to be limited in order to prevent it from compromising your system or network. For example, HTTP enforces a policy called [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) so that servers a page sends a request to can opt out of connections from sites operated by other servers. This keeps web pages from creating nuisance or abusive traffic on the network.

**Comment by guest271314** [comment]
> Closing this issue because supporting connections to TCP servers from arbitrary web pages is a non-goal for the Direct Sockets API.

Too late. That's already inherently possible with Direct Sockets API.

> HTTP and WebSockets are "just wrappers" around a TCP connection however they intentionally limit the hosts that a page can connect to. Remember that a web page can run arbitrary code on your computer. This code has to be limited in order to prevent it from compromising your system or network. For example, HTTP enforces a policy called [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) so that servers a page sends a request to can opt out of connections from sites operated by other servers. This keeps web pages from creating nuisance or abusive traffic on the network.

There's no way for you to prevent this. There are far too many ways to exchange data with an Isolated Web App using Web extension code or just Web API's.

As I've said before I think it's a horrible idea to try to gate one API behind another API. 

I am far more motivated to get to Direct Sockets API for my own use cases than Isolated Web Apps. Thus you have set up a kind of honey pot here. Hack IWA's by any means necessary to get to Direct Sockets API.

**Comment by guest271314** [comment]
@allurx 

> As a Java programmer, I just want to transmit data through a socket channel to a simple HTML and JavaScript page I created (I don’t want to use HTTP, WebSocket, or spend too much time studying front-end technologies).

Just process the HTTP or WebSocket over TCP. Then you can communicate with Direct Sockets `TCPServerSocket` from any arbitrary Web page. See https://github.com/guest271314/direct-sockets-http-ws-server.
