### ISSUE TITLE
Add examples generating keys with Web Cryptography API and building with Deno and Bun

### ISSUE THREAD

**Issue by guest271314** [GoogleChromeLabs/telnet-client#36]
The keys can be generated using Web Cryptography API using `deno` and `bun`. `node` and `openssl` are not necessary to generate keys or build an IWA.

**Comment by reillyeon** [comment]
Ok.

**Comment by guest271314** [comment]
> Ok.

> [reillyeon](https://github.com/reillyeon) closed this as [not planned](https://github.com/GoogleChromeLabs/telnet-client/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22) [1 minute ago](https://github.com/GoogleChromeLabs/telnet-client/issues/36#event-12333912799)

Does that mean "no"?
