### ISSUE TITLE
FYI: HTTP and WebSocket servers over TCPServerSocket

### ISSUE THREAD

**Issue by guest271314** [GoogleChromeLabs/telnet-client#37]
- Original HTTP server https://gist.github.com/guest271314/73a50e9ebc6acaaff5d39f6fc7918ebf
- HTTP and WebSocket (W.I.P., still working on normal close instead of aborting the request) server https://gist.github.com/robertrypula/b813ffe23a9489bae1b677f1608676c8?permalink_comment_id=5032239#gistcomment-5032239

**Comment by reillyeon** [comment]
Closing as off-topic since this is the demo app repo but if you get this code published somewhere other developers can pull it from it would be interesting to link to as an example in the Direct Sockets documentation.

**Comment by guest271314** [comment]
@reillyeon https://github.com/guest271314/direct-sockets-http-ws-server

**Comment by guest271314** [comment]
@reillyeon Any reason why Chromium is now blocking IWA's from being launched with `window.open()`? https://issues.chromium.org/issues/339994757
