### ISSUE TITLE
TCPSocket and TCPServerSocket stopped working on Chromium 131

### ISSUE THREAD

**Issue by guest271314** [GoogleChromeLabs/telnet-client#50]
```
Uncaught (in promise) InvalidAccessError: Access to the requested host or port is blocked.
```

This is including with `"direct-sockets-private"` policy.

What's going on?

**Comment by guest271314** [comment]
This is what I had in the file

```
  const socket = new TCPServerSocket("0.0.0.0", {
    localPort: 8080,
  });
```

Looks like that doesn't work anymore.

These do work in DevTools of the IWA

```
socket = new TCPServerSocket("::");
```

```
socket = new TCPServerSocket("0.0.0.0");
```

Did something change for setting `localPort` directly?

**Comment by reillyeon** [comment]
Based on security review feedback we've added a restriction on listening to ports below 32,768. This is discussed in https://github.com/WICG/direct-sockets/pull/74. Closing this issue as off-topic, since this demo is unaffected by the change.

**Comment by guest271314** [comment]
That's it. Thanks. Would be helpful if you folks kept track of all of these disparate, interlocking updates to IWA and DS in one place.
